### ISSUE TITLE
Clarity issues

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#36]
Some beta-testers don't understand that instructions are applied to the transformed dataset, not the original one. They should press the reset button if they want to work on the original dataset.

Also beta-testers do not understand that table-values have to be precise in the instruction as they are unknown to the model: you can't enter "LA" if the dataset only contains "Los Angeles"

We need to find a way to address these issues through UX, notifications or other fixes

**Comment by Jonisa2022** [comment]
I think there are a few ways to address these issues. One way would be to add a notification that appears when the user tries to apply an instruction to the original dataset. The notification could explain that the instructions are applied to the transformed dataset and that the user needs to press the reset button if they want to work on the original dataset.
Another way to address this issue would be to change the default behavior of the application so that it always starts with the transformed dataset. This would mean that the user would need to manually press the reset button if they wanted to work on the original dataset.
Finally, we could also add a feature that allows the user to specify whether they want to apply the instructions to the original dataset or the transformed dataset. This would give the user more control over the application and would help to prevent confusion.

**Comment by AlexandreSajus** [comment]
Thanks a lot for the great feedback! I'll probably start with the notification route, and I'll see if it's enough in beta-testing

**Comment by AlexandreSajus** [comment]
Closing this, refer to #41
